 const data=[
    {
        name:"Trident",
        label:"Trident",
        ProjectPlotArea:"7.5 Acers",
        GreenArea:"70%",
        PropertyStatus:"Ready To Move",
        PriceRange:"34 Lacs -1.2 Cr",
        TotalTowers:"12",
        TotalFlats:"1200",
        OCStatus:"A to I Received",
        Density:"-",
        PodiumNonPodium:"Podium",
        ApprovedBank:"SBI,PNB,HDFC",
        ClubHouseSize:"10,000 sqft",
        ConstructionType:"Bricks",
        TowerHeights:"A,B,C-25/ D,E,F -19/ G,H,I,J,K,L-22",
        LiftperTower:"2 in Each",
        FloorvsFlats:"A,B,G-6/ C-4/ D,E,F,H,I,J,K,L-4",
        PossessionDate:"2017",
        Lobby:"-",
        Distance:"-",
        Segment:"Economic"
    },{
        name:"Ace Divino",
        label:"Ace Divino",
        ProjectPlotArea:"10.41 Acers",
        GreenArea:"75%",
        PropertyStatus:"Under Construction",
        PriceRange:"35 Lacs - 59 Lacs",
        TotalTowers:"11",
        TotalFlats:"1748",
        OCStatus:"Not Applied",
        Density:"-",
        PodiumNonPodium:"Non Podium",
        ApprovedBank:"-",
        ClubHouseSize:"25,000 sqft",
        ConstructionType:"Mivan Framework",
        TowerHeights:"Tower 1,2 ,3,4,5,6,7,8,9,10,11-G+22",
        LiftperTower:"3 in Each",
        FloorvsFlats:"Tower 1,2,3,4,10,11- 6Flats / Tower 5,6,7,8,9 - 8 flats",
        PossessionDate:"Aug-2022",
        Lobby:"-",
        Distance:"-",
        Segment:"Luxury"
    },{
        name:"Reso",
        label:"Reso",
        ProjectPlotArea:"3.25 Acres",
        GreenArea:"",
        PropertyStatus:"Under Construction",
        PriceRange:"",
        TotalTowers:"5",
        TotalFlats:"580",
        OCStatus:"Not Applied",
        Density:"-",
        PodiumNonPodium:"Podium",
        ApprovedBank:"-",
        ClubHouseSize:"12,000 sqft",
        ConstructionType:"Mivan Framework",
        TowerHeights:"Tower 1-23, Rest 22",
        LiftperTower:"2 in Each",
        FloorvsFlats:"Tower 1,5 - 4 Flats / Tower 2,3,4 - 6 Flats",
        PossessionDate:"",
        Lobby:"-",
        Distance:"-",
        Segment:"Luxury"
    }
]

export default data;